name = "sgf-parsing"
version = "0.1.0"
defaultTargets = ["SgfParsingTest"]
testDriver = "SgfParsingTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "SgfParsing"

[[lean_exe]]
name = "SgfParsingTest"
root = "SgfParsingTest"
