name = "zebra-puzzle"
version = "0.1.0"
defaultTargets = ["ZebraPuzzleTest"]
testDriver = "ZebraPuzzleTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "ZebraPuzzle"

[[lean_exe]]
name = "ZebraPuzzleTest"
root = "ZebraPuzzleTest"
