name = "dominoes"
version = "0.1.0"
defaultTargets = ["DominoesTest"]
testDriver = "DominoesTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "Dominoes"

[[lean_exe]]
name = "DominoesTest"
root = "DominoesTest"
