name = "crypto-square"
version = "0.1.0"
defaultTargets = ["CryptoSquareTest"]
testDriver = "CryptoSquareTest"

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "CryptoSquare"

[[lean_exe]]
name = "CryptoSquareTest"
root = "CryptoSquareTest"
